### ISSUE TITLE
Unfinished sentence in Week 3 Building Custom Graphics reading

### ISSUE THREAD

**Issue by jacobtnyoung** [DS4PS/cpp-526-sum-2020#31]
In section 1.3.7 Highlighting Groups, the sentence "Perhaps we have a theory that corn-fed players that grew up in Iowa" just stops. I think this is suppose to have some explanation of highlighting players from IOWA.

**Comment by jacobtnyoung** [comment]
Moved this to the textbook issues page.

**Comment by jamisoncrawford** [comment]
@jacobtnyoung we need to start compensating you - thanks!
