### ISSUE TITLE
Lab01- Knitting Issue

### ISSUE THREAD

**Issue by gzbib** [DS4PS/cpp-526-sum-2020#7]
Hello,

I was trying to knit the RMD file but I keep getting the below error message. Any thoughts?

Thanks in advance.
![Knitting](https://user-images.githubusercontent.com/60263729/82800708-c834da00-9e84-11ea-94a5-83666f00db6a.PNG)

**Comment by jamisoncrawford** [comment]
@gzbib are you all set? Looks like the dataset in object `dat` was not read in before you called it on line 29.

**Comment by gzbib** [comment]
All is set Sir, i ran the chunks all over again but I kept getting the same
error so I added eval=False for the 2 problematic chunks and the knitting
worked. I am not sure what was the issue.

Thanks a lot

**Comment by jamisoncrawford** [comment]
According to your error message, `object 'dat' not found` means that one of your code chunks used the object `dat`, which contains the tax parcel data, but at that point in the script, `dat` was not yet loaded.  For your lab to still "work", with all the solutions, it must mean that `dat` was loaded into a code chunk after the chunks that were giving you issues.  It's all very linear and each chunk builds off the previous one, so I assume that's the core of the issue.  Looking forward to grading and smart thinking with `eval = FALSE`!
